services:
  postgres:
    image: postgres:15
    container_name: olist-postgres
    env_file:
      - ./config/.env
    ports:
      - "5432:5432"

    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_replication_slots=10"
      - "-c"
      - "max_wal_senders=10"
    volumes:
      - ./pgdata:/var/lib/postgresql/data


  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"   # host access
      - "9093:9093"   # controller
    environment:
      # --- KRaft essentials ---
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "1"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      # --- Listeners (host + internal + controller) ---
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT_INTERNAL"

      # --- Lab-friendly settings ---
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1 || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 60
    volumes:
      - ./kafkadata:/var/lib/kafka/data


  connect:
    image: quay.io/debezium/connect:2.7
    container_name: connect
    restart: unless-stopped
    depends_on:
      - kafka
      - postgres
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: "kafka:29092"
      GROUP_ID: "connect-cluster"
      CONFIG_STORAGE_TOPIC: "connect-configs"
      OFFSET_STORAGE_TOPIC: "connect-offsets"
      STATUS_STORAGE_TOPIC: "connect-statuses"

      CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      STATUS_STORAGE_REPLICATION_FACTOR: "1"

      KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
    healthcheck:
      test: [ "CMD-SHELL", "curl -sf http://localhost:8083/ >/dev/null || exit 1" ]
      interval: 5s
      timeout: 2s
      retries: 60

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.1
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka:29092"
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: "1"

   #dodanie connectorów
  connect-init:
    image: mcr.microsoft.com/powershell:7.4-alpine-3.17
    depends_on:
      wait-ready:
        condition: service_completed_successfully
    volumes:
       - ./connectors:/connectors:ro
    entrypoint: [ "pwsh","-File","/connectors/register.ps1" ]
    restart: "no"

  wait-ready:
    image: curlimages/curl:8.6.0
    depends_on:
      - kafka
      - connect
    entrypoint: [ "sh", "-lc" ]
    command: >
      echo "Waiting for Kafka DNS..." ;
      until (getent hosts kafka >/dev/null 2>&1); do sleep 1; done ;
      echo "Waiting for Connect..." ;
      until curl -sf http://connect:8083/ >/dev/null; do sleep 2; done ;
      echo "READY"
    restart: "no"

  spark:
    image: apache/spark:3.5.1
    container_name: spark
    depends_on:
      - kafka
    volumes:
      - ./src/spark:/opt/spark-app
      - spark-ivy:/tmp/.ivy2
    working_dir: /opt/spark-app
    entrypoint: [ "sleep", "infinity" ]

  spark-job:
    image: apache/spark:3.5.1
    container_name: spark-job
    user: "0:0"
    depends_on:
      wait-ready:
        condition: service_completed_successfully
      minio-init:
        condition: service_completed_successfully
    volumes:
      - ./src/spark:/opt/spark-app
      - spark-ivy:/tmp/.ivy2
      - ./spark/checkpoints:/opt/spark-app/checkpoints
    working_dir: /opt/spark-app
    entrypoint: [ "sh", "-lc" ]
    command:
      - "/opt/spark/bin/spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,org.apache.commons:commons-pool2:2.11.1,org.apache.kafka:kafka-clients:3.4.1,io.delta:delta-spark_2.12:3.2.0,org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262 --conf spark.jars.ivy=/tmp/.ivy2 --conf spark.driver.extraClassPath=/tmp/.ivy2/jars/* --conf spark.executor.extraClassPath=/tmp/.ivy2/jars/* --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=minioadmin --conf spark.hadoop.fs.s3a.secret.key=minioadmin --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --conf spark.hadoop.fs.s3a.connection.ssl.enabled=false /opt/spark-app/job_orders_stream.py"
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # UI
    volumes:
      - minio_data:/data
    networks:
      - default

  minio-init:
    image: minio/mc:latest
    container_name: minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      mc alias set local http://minio:9000 minioadmin minioadmin;
      mc mb -p local/datalake || true;
      mc ls local;
      "
    networks:
      - default

  spark-shell:
    image: apache/spark:3.5.1
    container_name: spark-shell
    user: "0:0"
    depends_on:
      minio-init:
        condition: service_completed_successfully
      wait-ready:
        condition: service_completed_successfully
    volumes:
      - spark-ivy:/tmp/.ivy2
    entrypoint: [ "sh", "-lc" ]
    environment:
      SPARK_SHELL_OPTS: >
        --packages io.delta:delta-spark_2.12:3.2.0,org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262
        --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension
        --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog
        --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000
        --conf spark.hadoop.fs.s3a.access.key=minioadmin
        --conf spark.hadoop.fs.s3a.secret.key=minioadmin
        --conf spark.hadoop.fs.s3a.path.style.access=true
        --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
        --conf spark.hadoop.fs.s3a.connection.ssl.enabled=false
    command: >
      bash -lc '/opt/spark/bin/spark-shell $SPARK_SHELL_OPTS'
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  kafka-data:
  spark-ivy:
  spark-jars:
  minio_data: